# Generated by Django 4.0.6 on 2022-07-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='answer',
            field=models.ManyToManyField(blank=True, related_name='user_answer', to='user_test.answer'),
        ),
    ]
